import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
const desp = Montserrat({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Todo nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={desp.className}>
        <Navbar/>
        <main className="max-container ">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
