import { Alata } from "next/font/google";
import "./globals.css";

const disp = Alata({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Todo nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={disp.className}>{children}</body>
    </html>
  );
}
